create table users
(
    chat_id       bigint not null,
    user_name     varchar(255),
    first_name    varchar(255),
    last_name     varchar(255),
    phone_number  varchar(255),
    language      varchar(255),
    privilege     integer,
    registered_at timestamp(6),
    primary key (chat_id)
);
create table categories
(
    category_id      bigint generated by default as identity,
    category_name_en varchar(255),
    category_name_ro varchar(255),
    category_day_of_week boolean,
    primary key (category_id)
);
create table products
(
    product_id        bigint not null,
    product_name_en   varchar(255),
    product_name_ro   varchar(255),
    product_price     numeric(38,2),
    product_descr_en  TEXT,
    product_descr_ro  TEXT,
    product_available boolean,
    category_id       bigint not null,
    primary key (product_id)
);
create table orders
(
    order_id    bigint generated by default as identity,
    quantity    varchar(255),
    total_price numeric(38,2),
    status      varchar(255),
    created_at  timestamp(6),
    finished_at timestamp(6),
    user_id     bigint not null,
    product_id  bigint not null,
    primary key (order_id)
);
alter table if exists orders add constraint FKkp5k52qtiygd8jkag4hayd0qg foreign key (product_id) references products;
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories;
