name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Maven project
        run: mvn clean install -DskipTests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Tag Docker image
        run: |
          docker build -t docker-spring-boot .
          docker tag docker-spring-boot:latest dima01211/shopbot:latest
      - name: Test in Docker Compose with env
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
          PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
          PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
        run: docker-compose -f docker-compose/docker-compose.yml up -d
      - name: Wait for web service to become healthy
        run: |
          for i in {1..30}; do
            if [ "$(docker inspect --format='{{json .State.Health.Status}}' $(docker-compose -f docker-compose/docker-compose.yml ps -q app))" == '"healthy"' ]; then
               echo "Service is healthy!"
            exit 0
            fi
             echo "Waiting for service to become healthy..."
                sleep 10
              done
            echo "Service did not become healthy in time."
              exit 1
      - name: Display Docker Compose logs
        run: docker-compose -f docker-compose/docker-compose.yml logs app
      - name: Teardown Docker Compose
        if: always()
        run: docker-compose -f docker-compose/docker-compose.yml down
      - name: Push Docker image
        run: |
          docker push dima01211/shopbot:latest
